#!/bin/bash
source "`dirname "${0}"`/munkiwebadmin-config"
SUBMITURL="${MWA_HOST}/update"

RUNTYPE="$1"
if [ -z "$RUNTYPE" ]; then
    RUNTYPE="reportbrokenclient"
fi
MAC=`ifconfig en0 | awk '/ether/ {print $2}'`
NAME=`/usr/sbin/scutil --get ComputerName`

mwa_curl --max-time 5 \
    -d runtype="$RUNTYPE" \
    -d mac="$MAC" \
    -d name="$NAME" \
    "$SUBMITURL/report_broken_client"

exit 0
